### ISSUE TITLE
Check if partsize is valid when multipart upload

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-qingstor#4]
We should check whether partsize is valid when multipart upload. Because QingStor has max parts limit 10000. So the part number will exceed the limit if part size is too small.
It is necessary to check validity before multipart upload started.

**Comment by Xuanwo** [comment]
We should do the following things:

- [ ] Add const for part limits
- [ ] Pollute limits into the part object

**Comment by xiongjiwei** [comment]
I want to work on this but I got some questions after reading `QingStor` doc. If the part number is bigger than 10000, the server will report the error, why we need to check it here? Or, I just misunderstand this issue? Can you please give me some examples of invalid usage to make me understand it clearly?

**Comment by Xuanwo** [comment]
As you said, different services have different restrictions. go-storage's purpose is to build an abstract storage layer for all services, so we need to provide a way for users to get the limitations so that they can adapt their input to make sure they upload their files successfully. 

And it's more user-friendly that return an error before sending a request instead of returning an error after the user has already sent 5GB content. 

This issue has been fixed partially in https://github.com/aos-dev/go-service-qingstor/pull/34, so what we need to do is check the part number before calling `UploadPart`.

**Comment by Xuanwo** [comment]
Finished in #58
